<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Common">
      <HintPath>..\..\Healthcare-Common\bin\Debug\net10.0\Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
